<?php
// Danh sách loại giấy tờ / hồ sơ đất đai (3 nhóm chính)
// Bản đã chỉnh sửa: 2026-05-19
// Nguyên tắc:
// - GCN: chỉ cho điểm cao với tiêu đề/đặc trưng thật sự của Giấy chứng nhận quyền sử dụng đất.
// - GTPL: quyết định, hợp đồng, đơn, trích lục bản đồ/khu đất, đăng ký kinh doanh, bản sao/chứng thực.
// - NVTC: thuế, lệ phí trước bạ, giấy nộp tiền, thông báo nộp tiền, phiếu chuyển thông tin tài chính.
return [
    'GCN' => [
        'name'  => 'Giấy chứng nhận',
        'short' => 'Giấy chứng nhận',
        'color' => '#22c55e',
        'keywords' => [
            // Cụm mạnh của GCN đất
            'giấy chứng nhận quyền sử dụng đất' => 45,
            'giay chung nhan quyen su dung dat' => 45,
            'giấy chứng nhận quyền sử dụng đất quyền sở hữu nhà ở' => 45,
            'giay chung nhan quyen su dung dat quyen so huu nha o' => 45,
            'số vào sổ cấp giấy chứng nhận quyền sử dụng đất' => 42,
            'so vao so cap giay chung nhan quyen su dung dat' => 42,
            'số vào sổ cấp giấy chứng nhận' => 35,
            'so vao so cap giay chung nhan' => 35,
            'số vào sổ cấp gcn' => 35,
            'so vao so cap gcn' => 35,
            'số phát hành' => 28,
            'so phat hanh' => 28,
            'gcn số' => 25,
            'gcn so' => 25,



            // GCN mẫu mới nền hồng bảo an
            'quyền sử dụng đất quyền sở hữu nhà ở và tài sản khác gắn liền với đất' => 50,
            'quyen su dung dat quyen so huu nha o va tai san khac gan lien voi dat' => 50,
            'quyền sở hữu nhà ở và tài sản khác gắn liền với đất' => 45,
            'quyen so huu nha o va tai san khac gan lien voi dat' => 45,
            'người sử dụng đất, chủ sở hữu nhà ở và tài sản khác gắn liền với đất' => 40,
            'nguoi su dung dat chu so huu nha o va tai san khac gan lien voi dat' => 40,
            'không được sửa chữa, tẩy xóa hoặc bổ sung bất kỳ nội dung nào' => 30,
            'khong duoc sua chua tay xoa hoac bo sung bat ky noi dung nao' => 30,
            'mã vạch' => 15,
            'ma vach' => 15,


            // GCN trắng đen / scan mất màu
            'vi- những thay đổi sau khi cấp giấy chứng nhận quyền sử dụng đất' => 45,
            'vi nhung thay doi sau khi cap giay chung nhan quyen su dung dat' => 45,
            'vi. những thay đổi sau khi cấp giấy chứng nhận quyền sử dụng đất' => 45,
            'người được cấp giấy chứng nhận quyền sử dụng đất cần chú ý' => 42,
            'nguoi duoc cap giay chung nhan quyen su dung dat can chu y' => 42,
            'nội dung thay đổi và cơ sở pháp lý' => 35,
            'noi dung thay doi va co so phap ly' => 35,
            'xác nhận của cơ quan có thẩm quyền' => 30,
            'xac nhan cua co quan co tham quyen' => 30,

            // Trang ruột/trang sau GCN
            'sơ đồ thửa đất' => 30,
            'so do thua dat' => 30,
            'v. sơ đồ thửa đất' => 35,
            'v- sơ đồ thửa đất' => 35,
            'v so do thua dat' => 35,
            'những thay đổi sau khi cấp giấy chứng nhận quyền sử dụng đất' => 42,
            'nhung thay doi sau khi cap giay chung nhan quyen su dung dat' => 42,
            'vi. những thay đổi sau khi cấp giấy chứng nhận quyền sử dụng đất' => 45,
            'vi- những thay đổi sau khi cấp giấy chứng nhận quyền sử dụng đất' => 45,
            'vi nhung thay doi sau khi cap giay chung nhan quyen su dung dat' => 45,
            'nội dung thay đổi và cơ sở pháp lý' => 32,
            'noi dung thay doi va co so phap ly' => 32,
            'xác nhận của cơ quan có thẩm quyền' => 25,
            'xac nhan cua co quan co tham quyen' => 25,
            'người được cấp giấy chứng nhận quyền sử dụng đất cần chú ý' => 38,
            'nguoi duoc cap giay chung nhan quyen su dung dat can chu y' => 38,

            // Nội dung đặc trưng trong GCN
            'i. tên người sử dụng đất' => 25,
            'i- tên người sử dụng đất' => 25,
            'i ten nguoi su dung dat' => 25,
            'ii. thửa đất được quyền sử dụng' => 30,
            'ii- thửa đất được quyền sử dụng' => 30,
            'ii thua dat duoc quyen su dung' => 30,
            'thửa đất được quyền sử dụng' => 28,
            'thua dat duoc quyen su dung' => 28,
            'iii. tài sản gắn liền với đất' => 22,
            'iii- tài sản gắn liền với đất' => 22,
            'iii tai san gan lien voi dat' => 22,
            'iv. ghi chú' => 15,
            'iv- ghi chú' => 15,
            'iv ghi chu' => 15,
            'mục đích sử dụng' => 15,
            'muc dich su dung' => 15,
            'thời hạn sử dụng' => 15,
            'thoi han su dung' => 15,
            'nguồn gốc sử dụng' => 15,
            'nguon goc su dung' => 15,
            'tài sản gắn liền với đất' => 15,
            'tai san gan lien voi dat' => 15,

            // Cơ quan ký/cấp thường gặp trên GCN
            'tm. ubnd tỉnh bình định' => 20,
            'tm ubnd tinh binh dinh' => 20,
            'giám đốc sở tài nguyên và môi trường' => 20,
            'giam doc so tai nguyen va moi truong' => 20,
            'chủ tịch ủy ban nhân dân' => 15,
            'chu tich uy ban nhan dan' => 15,
            'ủy ban nhân dân tỉnh bình định' => 18,
            'uy ban nhan dan tinh binh dinh' => 18,

            // Bản đồ trên GCN
            'tỷ lệ 1/1000' => 14,
            'ty le 1/1000' => 14,
            'tỷ lệ 1/2000' => 14,
            'ty le 1/2000' => 14,
            'ranh giới sử dụng' => 10,
            'ranh gioi su dung' => 10,
            'ranh giới sử dụng đất' => 15,
            'ranh gioi su dung dat' => 15,

            // Biến thể OCR sai nhưng vẫn đặc trưng GCN
            'giay chung nhan quyen sd dat' => 38,
            'giay chung nhan quyen su dung dât' => 35,
            'giay chung nhan quyen su dung đat' => 35,
            'giay chưng nhan quyen su dung dat' => 35,
            'giay chung nhan quyên su dung dat' => 35,
            'so vao so cap giay chung nhan quyen sd dat' => 35,
            'nguoi duoc cap giay chung nhan can chu y' => 30,
            'nhung thay doi sau khi cap giay chung nhan' => 30,

            // Từ khóa chung: để điểm thấp, tránh nhầm GTPL/NVTC thành GCN
            'giấy chứng nhận' => 6,
            'giay chung nhan' => 6,
            'giấy chứng' => 4,
            'giay chung' => 4,
            'chứng nhận' => 18,
            'chung nhan' => 18,
            'quyền sử dụng đất' => 5,
            'quyen su dung dat' => 5,
            'sử dụng đất' => 3,
            'su dung dat' => 3,
            'thửa đất' => 3,
            'thua dat' => 3,
            'diện tích' => 3,
            'dien tich' => 3,
        ],
    ],

    'GTPL' => [
        'name'  => 'Giấy tờ pháp lý',
        'short' => 'Giấy tờ pháp lý',
        'color' => '#3b82f6',
        'keywords' => [
            // Hợp đồng thuê đất / hợp đồng thuê đất bổ sung
            'hợp đồng thuê đất bổ sung' => 45,
            'hop dong thue dat bo sung' => 45,
            'hợp đồng thuê đất' => 40,
            'hop dong thue dat' => 40,
            'thuê đất bổ sung' => 35,
            'thue dat bo sung' => 35,
            'hợp đồng bổ sung' => 30,
            'hop dong bo sung' => 30,
            'hợp đồng số' => 22,
            'hop dong so' => 22,
            'số hợp đồng thuê đất' => 25,
            'so hop dong thue dat' => 25,
            'hđ-tđ' => 30,
            'hd-td' => 30,
            'hdtđ' => 30,
            'hdtd' => 30,
            'bên cho thuê đất' => 30,
            'ben cho thue dat' => 30,
            'bên thuê đất' => 30,
            'ben thue dat' => 30,
            'hai bên thỏa thuận ký hợp đồng thuê đất bổ sung' => 40,
            'hai ben thoa thuan ky hop dong thue dat bo sung' => 40,
            'điều chỉnh tên tổ chức được thuê đất' => 35,
            'dieu chinh ten to chuc duoc thue dat' => 35,
            'làm cửa hàng sách' => 25,
            'lam cua hang sach' => 25,
            'thuê đất làm cửa hàng sách' => 30,
            'thue dat lam cua hang sach' => 30,
            'hop dong thue dat bo xung' => 35,
            'hợp đồng thuê đất bổ xung' => 35,
            'hợp đồng thuế đất' => 25,
            'hợp đồng thuê đắt' => 25,

            // Trích lục bản đồ / trích lục khu đất: luôn thuộc GTPL
            'trích lục bản đồ' => 55,
            'trich luc ban do' => 55,
            'trích lục bản đồ địa chính' => 60,
            'trich luc ban do dia chinh' => 60,
            'trích lục bản đồ khu đất' => 60,
            'trich luc ban do khu dat' => 60,
            'trích lục khu đất' => 60,
            'trich luc khu dat' => 60,
            'trích lục thửa đất' => 45,
            'trich luc thua dat' => 45,
            'bản đồ địa chính' => 40,
            'ban do dia chinh' => 40,
            'khu đất bồi thường' => 40,
            'khu dat boi thuong' => 40,
            'khu đất xin cấp giấy chứng nhận' => 40,
            'khu dat xin cap giay chung nhan' => 40,
            'ranh giới khu đất' => 35,
            'ranh gioi khu dat' => 35,
            'người trích lục' => 60,
            'nguoi trich luc' => 60,
            'người trích lục bản đồ' => 65,
            'nguoi trich luc ban do' => 65,
            'người trích lục khu đất' => 65,
            'nguoi trich luc khu dat' => 65,
            'người kiểm tra' => 35,
            'nguoi kiem tra' => 35,
            'sở địa chính tỉnh bình định' => 25,
            'so dia chinh tinh binh dinh' => 25,
            'trich luc ban do khudat' => 45,
            'trichluc ban do khu dat' => 45,
            'trich luc ban ho khu dat' => 35,
            'trich luc ban d0 khu dat' => 35,

            // Giấy chứng nhận đăng ký kinh doanh: không phải GCN đất
            'giấy chứng nhận đăng ký kinh doanh' => 60,
            'giay chung nhan dang ky kinh doanh' => 60,
            'đăng ký kinh doanh' => 45,
            'dang ky kinh doanh' => 45,
            'phòng đăng ký kinh doanh' => 40,
            'phong dang ky kinh doanh' => 40,
            'sở kế hoạch và đầu tư' => 35,
            'so ke hoach va dau tu' => 35,
            'sở kế hoạch và đầu tư tỉnh bình định' => 40,
            'so ke hoach va dau tu tinh binh dinh' => 40,
            'công ty cổ phần' => 30,
            'cong ty co phan' => 30,
            'đăng ký lần đầu' => 25,
            'dang ky lan dau' => 25,
            'tên công ty' => 18,
            'ten cong ty' => 18,
            'tên giao dịch' => 18,
            'ten giao dich' => 18,
            'tên viết tắt' => 18,
            'ten viet tat' => 18,
            'địa chỉ trụ sở chính' => 18,
            'dia chi tru so chinh' => 18,
            'giấy đăng ký kinh doanh' => 40,
            'giay dang ky kinh doanh' => 40,
            'giấy phép đầu tư' => 25,
            'giay phep dau tu' => 25,
            'giay chung nhan dang ky kinh doan' => 45,
            'giay chung nhan dangky kinh doanh' => 45,
            'giay chung nhan dang ki kinh doanh' => 45,

            // Đơn đăng ký biến động / Mẫu số 14/ĐK / hướng dẫn viết đơn
            'đơn xin đăng ký biến động về sử dụng đất' => 65,
            'don xin dang ky bien dong ve su dung dat' => 65,
            'đơn đăng ký biến động về sử dụng đất' => 60,
            'don dang ky bien dong ve su dung dat' => 60,
            'đăng ký biến động về sử dụng đất' => 55,
            'dang ky bien dong ve su dung dat' => 55,
            'đơn xin đăng ký biến động' => 45,
            'don xin dang ky bien dong' => 45,
            'đơn đăng ký biến động' => 45,
            'don dang ky bien dong' => 45,
            'mẫu số 14/đk' => 60,
            'mau so 14/dk' => 60,
            'mẫu số 14 đk' => 55,
            'mau so 14 dk' => 55,
            'mẫu số 14đk' => 55,
            'mau so 14đk' => 55,
            'phần ghi của người nhận hồ sơ' => 45,
            'phan ghi cua nguoi nhan ho so' => 45,
            'kê khai của người sử dụng đất' => 55,
            'ke khai cua nguoi su dung dat' => 55,
            'nội dung xin đăng ký biến động' => 55,
            'noi dung xin dang ky bien dong' => 55,
            'nội dung đăng ký biến động' => 50,
            'noi dung dang ky bien dong' => 50,
            'giấy chứng nhận quyền sử dụng đất đã cấp' => 45,
            'giay chung nhan quyen su dung dat da cap' => 45,
            'giấy chứng nhận qsdđ đã cấp' => 45,
            'giay chung nhan qsdd da cap' => 45,
            'kết quả thẩm tra của văn phòng đăng ký quyền sử dụng đất' => 60,
            'ket qua tham tra cua van phong dang ky quyen su dung dat' => 60,
            'kết quả thẩm tra' => 35,
            'ket qua tham tra' => 35,
            'hướng dẫn viết đơn' => 55,
            'huong dan viet don' => 55,
            'đơn này dùng trong các trường hợp' => 45,
            'don nay dung trong cac truong hop' => 45,
            'thay đổi hạn chế quyền sử dụng đất' => 35,
            'thay doi han che quyen su dung dat' => 35,
            'thay đổi nghĩa vụ tài chính về đất đai' => 35,
            'thay doi nghia vu tai chinh ve dat dai' => 35,
            'người viết đơn ký và ghi rõ họ tên' => 30,
            'nguoi viet don ky va ghi ro ho ten' => 30,
            'don xin dang ki bien dong ve su dung dat' => 45,
            'don xin dang ky bien dong su dung dat' => 45,
            'don xin dangky bien dong ve su dung dat' => 40,



            // Đơn xin / Đơn đăng ký đất đai / Mẫu số 15/ĐK / Thông báo niêm yết: GTPL, không phải GCN
            'đơn xin xác nhận nguồn gốc đất' => 70,
            'don xin xac nhan nguon goc dat' => 70,
            'xác nhận nguồn gốc đất' => 55,
            'xac nhan nguon goc dat' => 55,
            'nguồn gốc đất' => 35,
            'nguon goc dat' => 35,
            'người làm đơn' => 45,
            'nguoi lam don' => 45,

            'đơn đăng ký đất đai, tài sản gắn liền với đất' => 75,
            'don dang ky dat dai tai san gan lien voi dat' => 75,
            'đơn đăng ký đất đai' => 65,
            'don dang ky dat dai' => 65,
            'đăng ký đất đai, tài sản gắn liền với đất' => 65,
            'dang ky dat dai tai san gan lien voi dat' => 65,
            'người sử dụng đất/người kê khai' => 45,
            'nguoi su dung dat nguoi ke khai' => 45,
            'người kê khai' => 40,
            'nguoi ke khai' => 40,

            'mẫu số 15/đk' => 65,
            'mau so 15/dk' => 65,
            'mẫu số 15 đk' => 60,
            'mau so 15 dk' => 60,
            'mẫu số 15' => 50,
            'mau so 15' => 50,
            'mẫu số 15a' => 50,
            'mau so 15a' => 50,
            'mẫu số 15b' => 50,
            'mau so 15b' => 50,
            'mẫu số 15c' => 50,
            'mau so 15c' => 50,

            'thông báo niêm yết công khai' => 65,
            'thong bao niem yet cong khai' => 65,
            'niêm yết công khai' => 55,
            'niem yet cong khai' => 55,
            'niêm yết công khai danh sách hồ sơ đăng ký đất đai' => 75,
            'niem yet cong khai danh sach ho so dang ky dat dai' => 75,
            'danh sách hồ sơ đăng ký đất đai' => 55,
            'danh sach ho so dang ky dat dai' => 55,
            'hồ sơ đăng ký đất đai' => 45,
            'ho so dang ky dat dai' => 45,
            'cấp gcn qsd đất' => 35,
            'cap gcn qsd dat' => 35,
            'quyền sở hữu tài sản gắn liền với đất lần đầu' => 45,
            'quyen so huu tai san gan lien voi dat lan dau' => 45,

            // Quyết định UBND / quyết định cho thuê đất / cổ phần hóa
            'quyết định của ubnd tỉnh' => 45,
            'quyet dinh cua ubnd tinh' => 45,
            'quyết định ubnd tỉnh' => 42,
            'quyet dinh ubnd tinh' => 42,
            'ủy ban nhân dân tỉnh bình định' => 25,
            'uy ban nhan dan tinh binh dinh' => 25,
            'ubnd tỉnh bình định' => 25,
            'ubnd tinh binh dinh' => 25,
            'chủ tịch ủy ban nhân dân tỉnh' => 30,
            'chu tich uy ban nhan dan tinh' => 30,
            'quyết định' => 35,
            'quyet dinh' => 35,
            'về việc cho thuê đất' => 45,
            've viec cho thue dat' => 45,
            'cho thuê đất và cấp giấy chứng nhận quyền sử dụng đất' => 55,
            'cho thue dat va cap giay chung nhan quyen su dung dat' => 55,
            'cấp giấy chứng nhận quyền sử dụng đất' => 35,
            'cap giay chung nhan quyen su dung dat' => 35,
            'công ty sách và thiết bị bình định' => 35,
            'cong ty sach va thiet bi binh dinh' => 35,
            'cửa hàng sách' => 25,
            'cua hang sach' => 25,
            'ký hợp đồng thuê đất' => 35,
            'ky hop dong thue dat' => 35,
            'sở địa chính' => 22,
            'so dia chinh' => 22,
            'phê duyệt phương án cổ phần hóa' => 45,
            'phe duyet phuong an co phan hoa' => 45,
            'phương án cổ phần hóa' => 42,
            'phuong an co phan hoa' => 42,
            'cổ phần hóa' => 38,
            'co phan hoa' => 38,
            'chuyển công ty nhà nước thành công ty cổ phần' => 40,
            'chuyen cong ty nha nuoc thanh cong ty co phan' => 40,
            'ban chỉ đạo cổ phần hóa' => 28,
            'ban chi dao co phan hoa' => 28,
            'trưởng ban chỉ đạo cổ phần hóa' => 25,
            'truong ban chi dao co phan hoa' => 25,

            // Bản sao / chứng thực
            'bản sao' => 30,
            'ban sao' => 30,
            'chứng thực bản sao đúng với bản chính' => 45,
            'chung thuc ban sao dung voi ban chinh' => 45,
            'chứng thực bản sao' => 38,
            'chung thuc ban sao' => 38,
            'số chứng thực' => 25,
            'so chung thuc' => 25,
            'quyển số' => 20,
            'quyen so' => 20,
            'sao y' => 18,
            'sao y bản chính' => 22,
            'sao y ban chinh' => 22,

            // Giấy tờ nhân thân / hộ tịch / giao dịch
            'chứng minh nhân dân' => 22,
            'chung minh nhan dan' => 22,
            'căn cước công dân' => 22,
            'can cuoc cong dan' => 22,
            'hộ khẩu' => 18,
            'ho khau' => 18,
            'sổ hộ khẩu' => 22,
            'so ho khau' => 22,
            'xác nhận cư trú' => 18,
            'xac nhan cu tru' => 18,
            'giấy khai sinh' => 18,
            'giay khai sinh' => 18,
            'giấy chứng nhận kết hôn' => 22,
            'giay chung nhan ket hon' => 22,
            'kết hôn' => 14,
            'ket hon' => 14,
            'ly hôn' => 14,
            'ly hon' => 14,
            'bản án' => 22,
            'ban an' => 22,
            'hợp đồng ủy quyền' => 28,
            'hop dong uy quyen' => 28,
            'văn bản ủy quyền' => 28,
            'van ban uy quyen' => 28,
            'giấy ủy quyền' => 25,
            'giay uy quyen' => 25,
            'hợp đồng mua bán' => 28,
            'hop dong mua ban' => 28,
            'hợp đồng tặng cho' => 28,
            'hop dong tang cho' => 28,
            'hợp đồng chuyển nhượng' => 30,
            'hop dong chuyen nhuong' => 30,
            'chuyển nhượng quyền sử dụng đất' => 30,
            'chuyen nhuong quyen su dung dat' => 30,
            'tặng cho quyền sử dụng đất' => 30,
            'tang cho quyen su dung dat' => 30,
            'thừa kế quyền sử dụng đất' => 28,
            'thua ke quyen su dung dat' => 28,
            'văn bản phân chia di sản' => 28,
            'van ban phan chia di san' => 28,
            'văn bản khai nhận di sản' => 28,
            'van ban khai nhan di san' => 28,

            // Hồ sơ đất đai cũ / giấy tờ pháp lý cũ
            'sổ địa chính' => 25,
            'so dia chinh' => 25,
            'hd so dia' => 22,
            'năm 1975' => 22,
            'nam 1975' => 22,
            'trước năm' => 22,
            'truoc nam' => 22,
            'thuộc thửa đất số' => 25,
            'thuoc thua dat so' => 25,
            'thuộc thửa đất' => 18,
            'thuoc thua dat' => 18,
            'công khai' => 18,
            'cong khai' => 18,
            'thống nhất' => 18,
            'thong nhat' => 18,
            'có tranh' => 18,
            'co tranh' => 18,
            'khiếu nại' => 18,
            'khieu nai' => 18,
            'khai sử dụng' => 18,
            'khai su dung' => 18,
            'khai sir dung' => 18,
            'đứng tên' => 18,
            'dung ten' => 18,
            'ding tên' => 18,
            'hợp đồng nay' => 18,
            'hop dong nay' => 18,

            // Từ khóa pháp lý chung, điểm thấp
            'đơn xin' => 18,
            'don xin' => 18,
            'đơn đăng ký' => 18,
            'don dang ky' => 18,
            'đơn đề nghị' => 18,
            'don de nghi' => 18,
            'căn cứ' => 8,
            'can cu' => 8,
            'xét đơn' => 10,
            'xet don' => 10,
            'theo đề nghị' => 10,
            'theo de nghi' => 10,
            'cộng hòa xã hội chủ nghĩa việt nam' => 3,
            'cong hoa xa hoi chu nghia viet nam' => 3,
            'độc lập tự do hạnh phúc' => 3,
            'doc lap tu do hanh phuc' => 3,
        ],
    ],

    'NVTC' => [
        'name'  => 'Nghĩa vụ tài chính',
        'short' => 'Nghĩa vụ tài chính',
        'color' => '#f97316',
        'keywords' => [
            // Nhận diện chính NVTC
            'nghĩa vụ tài chính' => 55,
            'nghia vu tai chinh' => 55,
            'xác định nghĩa vụ tài chính' => 60,
            'xac dinh nghia vu tai chinh' => 60,
            'để xác định nghĩa vụ tài chính' => 60,
            'de xac dinh nghia vu tai chinh' => 60,
            'thuế' => 35,
            'thue' => 35,
            'cơ quan thuế' => 45,
            'co quan thue' => 45,
            'chi cục thuế' => 50,
            'chi cuc thue' => 50,
            'cục thuế' => 40,
            'cuc thue' => 40,
            'kho bạc nhà nước' => 50,
            'kho bac nha nuoc' => 50,
            'kho bạc' => 35,
            'kho bac' => 35,

            // Giấy nộp tiền / biên lai / chứng từ nộp tiền
            'giấy nộp tiền' => 60,
            'giay nop tien' => 60,
            'giấy nộp tiền vào ngân sách nhà nước' => 70,
            'giay nop tien vao ngan sach nha nuoc' => 70,
            'cash deposit requirement' => 45,
            'cash collecting document' => 35,
            'vpbank' => 35,
            'ngân hàng nộp thay' => 45,
            'ngan hang nop thay' => 45,
            'nộp tiền' => 40,
            'nop tien' => 40,
            'người nộp tiền' => 38,
            'nguoi nop tien' => 38,
            'người nộp thuế' => 45,
            'nguoi nop thue' => 45,
            'mã số thuế' => 40,
            'ma so thue' => 40,
            'số tiền bằng chữ' => 35,
            'so tien bang chu' => 35,
            'tổng số tiền bằng chữ' => 40,
            'tong so tien bang chu' => 40,
            'số tiền' => 22,
            'so tien' => 22,
            'tài khoản nợ' => 20,
            'tai khoan no' => 20,
            'tài khoản có' => 20,
            'tai khoan co' => 20,
            'liên 2' => 15,
            'lien 2' => 15,
            'biên lai' => 45,
            'bien lai' => 45,

            // Thông báo nộp tiền sử dụng đất / thuê đất
            'thông báo nộp tiền sử dụng đất' => 70,
            'thong bao nop tien su dung dat' => 70,
            'thông báo nộp tiền' => 60,
            'thong bao nop tien' => 60,
            'nộp tiền sử dụng đất' => 60,
            'nop tien su dung dat' => 60,
            'tiền sử dụng đất' => 45,
            'tien su dung dat' => 45,
            'tiền thuê đất' => 45,
            'tien thue dat' => 45,
            'nộp tiền thuê đất' => 50,
            'nop tien thue dat' => 50,
            'số tiền sử dụng đất phải nộp' => 55,
            'so tien su dung dat phai nop' => 55,
            'số tiền thuê đất phải nộp' => 55,
            'so tien thue dat phai nop' => 55,
            'tổng số tiền phải nộp' => 50,
            'tong so tien phai nop' => 50,
            'số tiền phải nộp' => 45,
            'so tien phai nop' => 45,
            'hình thức nộp tiền' => 25,
            'hinh thuc nop tien' => 25,
            'chậm nộp' => 30,
            'cham nop' => 30,
            'phạt chậm nộp' => 45,
            'phat cham nop' => 45,
            'xử lý phạt chậm nộp tiền' => 55,
            'xu ly phat cham nop tien' => 55,

            // Lệ phí trước bạ nhà, đất
            'thông báo nộp lệ phí trước bạ nhà đất' => 70,
            'thong bao nop le phi truoc ba nha dat' => 70,
            'thông báo nộp lệ phí trước bạ nhà, đất' => 70,
            'thong bao nop le phi truoc ba nha, dat' => 70,
            'lệ phí trước bạ' => 60,
            'le phi truoc ba' => 60,
            'lệ phí trước bạ nhà đất' => 65,
            'le phi truoc ba nha dat' => 65,
            'tờ khai lệ phí trước bạ' => 60,
            'to khai le phi truoc ba' => 60,
            'tờ khai lệ phí trước bạ nhà đất' => 65,
            'to khai le phi truoc ba nha dat' => 65,
            'căn cứ tính lệ phí trước bạ' => 45,
            'can cu tinh le phi truoc ba' => 45,
            'nợ lệ phí trước bạ' => 40,
            'no le phi truoc ba' => 40,
            'ghi nợ lệ phí trước bạ' => 40,
            'ghi no le phi truoc ba' => 40,

            // Phiếu chuyển thông tin địa chính
            'phiếu chuyển thông tin địa chính' => 70,
            'phieu chuyen thong tin dia chinh' => 70,
            'phiếu chuyển thông tin' => 60,
            'phieu chuyen thong tin' => 60,
            'phiếu chuyển thông tin để xác định nghĩa vụ tài chính' => 75,
            'phieu chuyen thong tin de xac dinh nghia vu tai chinh' => 75,
            'phiếu chuyển thông tin nghĩa vụ tài chính' => 70,
            'phieu chuyen thong tin nghia vu tai chinh' => 70,
            'mẫu số 02/phiếu' => 30,
            'mau so 02/phieu' => 30,
            'mẫu số 04/phiếu' => 30,
            'mau so 04/phieu' => 30,
            'chuyển cho chi cục thuế' => 45,
            'chuyen cho chi cuc thue' => 45,
            'kính gửi chi cục thuế' => 45,
            'kinh gui chi cuc thue' => 45,
            'thông tin về nhà đất' => 35,
            'thong tin ve nha dat' => 35,
            'thông tin tài sản' => 25,
            'thong tin tai san' => 25,

            // Tờ khai thuế / tài chính
            'tờ khai thuế' => 45,
            'to khai thue' => 45,
            'tờ khai thuế thu nhập cá nhân' => 60,
            'to khai thue thu nhap ca nhan' => 60,
            'thuế thu nhập cá nhân' => 60,
            'thue thu nhap ca nhan' => 60,
            'thuế sử dụng đất' => 45,
            'thue su dung dat' => 45,
            'thuế nhà đất' => 45,
            'thue nha dat' => 45,
            'thuế nhà, đất' => 45,
            'thue nha, dat' => 45,
            'thuế chuyển quyền sử dụng đất' => 50,
            'thue chuyen quyen su dung dat' => 50,

            // Văn bản đề nghị nộp phạt / xác nhận nộp tiền
            'v/v đề nghị đơn vị nộp phạt' => 55,
            'v/v de nghi don vi nop phat' => 55,
            'đề nghị đơn vị nộp phạt' => 55,
            'de nghi don vi nop phat' => 55,
            'v/v nộp tiền sử dụng đất' => 50,
            'v/v nop tien su dung dat' => 50,
            'kính gửi kho bạc nhà nước' => 45,
            'kinh gui kho bac nha nuoc' => 45,
            'xác nhận về tổng số tiền' => 40,
            'xac nhan ve tong so tien' => 40,
            'đã nộp tổng số tiền' => 45,
            'da nop tong so tien' => 45,
            'đã nộp số tiền' => 40,
            'da nop so tien' => 40,
            'lcc' => 20,
            'ủy nhiệm chi' => 30,
            'uy nhiem chi' => 30,
            'chuyển khoản' => 30,
            'chuyen khoan' => 30,

            // Cơ quan/đơn vị hay xuất hiện trong hồ sơ tài chính
            'chi cục thuế tp. quy nhơn' => 45,
            'chi cuc thue tp. quy nhon' => 45,
            'chi cục thuế thành phố quy nhơn' => 45,
            'chi cuc thue thanh pho quy nhon' => 45,
            'cục thuế tỉnh bình định' => 40,
            'cuc thue tinh binh dinh' => 40,
            'kho bạc nhà nước thành phố quy nhơn' => 45,
            'kho bac nha nuoc thanh pho quy nhon' => 45,
            'văn phòng đăng ký quyền sử dụng đất' => 12,
            'van phong dang ky quyen su dung dat' => 12,

            // Cụm biểu mẫu thông báo thuế
            'i. thông tin về người nộp tiền' => 35,
            'i thong tin ve nguoi nop tien' => 35,
            'ii. thông tin về khoản thu' => 35,
            'ii thong tin ve khoan thu' => 35,
            'iii. tính phạt chậm nộp' => 35,
            'iii tinh phat cham nop' => 35,
            'phần xác định của chi cục thuế' => 45,
            'phan xac dinh cua chi cuc thue' => 45,
            'phần xử lý phạt chậm nộp tiền' => 45,
            'phan xu ly phat cham nop tien' => 45,
            'thủ trưởng cơ quan thu tiền' => 30,
            'thu truong co quan thu tien' => 30,
            'thủ trưởng cơ quan thuế' => 30,
            'thu truong co quan thue' => 30,

            // Số liệu tài chính
            'đồng' => 8,
            'dong' => 8,
            'bằng chữ' => 15,
            'bang chu' => 15,
            'triệu đồng' => 18,
            'trieu dong' => 18,
            'tỷ đồng' => 18,
            'ty dong' => 18,
            'nộp ngân sách' => 30,
            'nop ngan sach' => 30,
            'ngân sách nhà nước' => 40,
            'ngan sach nha nuoc' => 40,
            'khoản nộp ngân sách' => 30,
            'khoan nop ngan sach' => 30,
            'tài khoản thu ngân sách' => 30,
            'tai khoan thu ngan sach' => 30,
        ],
    ],
];
